enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

# Более гибкая стратегия для peer dependencies
pnpMode: loose

# Указываем yarn как разрешать пакеты
packageExtensions:
  "react-hot-toast@*":
    peerDependencies:
      "csstype": "*"
  "burner-connector@*":
    peerDependencies:
      "@tanstack/react-query": "*"
      "react": "*"
      "react-dom": "*" 
      "wagmi": "*"
  "daisyui@*":
    peerDependencies:
      "postcss": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

enableImmutableInstalls: false
