/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#008170",
          "primary-content": "#0F0F0F",
          secondary: "#005B41",
          "secondary-content": "#0F0F0F",
          accent: "#232D3F",
          "accent-content": "#0F0F0F",
          neutral: "#0F0F0F",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f4fff9",
          "base-300": "#e6fff7",
          "base-content": "#0F0F0F",
          info: "#008170",
          success: "#005B41",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#008170",
          "primary-content": "#F9FBFF",
          secondary: "#005B41",
          "secondary-content": "#F9FBFF",
          accent: "#232D3F",
          "accent-content": "#F9FBFF",
          neutral: "#F9FBFF",
          "neutral-content": "#232D3F",
          "base-100": "#232D3F",
          "base-200": "#1A2230",
          "base-300": "#0F0F0F",
          "base-content": "#F9FBFF",
          info: "#008170",
          success: "#005B41",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      colors: {
        'custom-black': '#0F0F0F',
        'custom-space': '#232D3F',
        'custom-teal': '#005B41',
        'custom-light-teal': '#008170',
      },
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
};
